# Generated by Django 5.2.7 on 2025-12-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConservacaoPescado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DestinoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('ordem', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PercepcaoCapturaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RendaPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimNao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Opção Sim / Não',
                'verbose_name_plural': 'Opções Sim / Não',
            },
        ),
        migrations.CreateModel(
            name='TurismoPescaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TurismoValorizaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_apelido', models.CharField(max_length=100, unique=True)),
                ('idade', models.PositiveSmallIntegerField()),
                ('tempo_pesca', models.PositiveSmallIntegerField(verbose_name='Tempo de pesca (em anos)')),
                ('outra_renda', models.CharField(blank=True, max_length=100)),
                ('quantidade_familiares', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qual_pos_captura', models.CharField(blank=True, max_length=100)),
                ('material_outro', models.CharField(blank=True, max_length=100)),
                ('zona_outro', models.CharField(blank=True, max_length=100)),
                ('especies_principais', models.TextField()),
                ('conservacao_outro', models.CharField(blank=True, max_length=100)),
                ('problema_outro', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conservacao', models.ManyToManyField(blank=True, to='main.conservacaopescado')),
                ('destino_descarte', models.ManyToManyField(blank=True, to='main.destinodescarte')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.escolaridade')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genero')),
                ('materiais', models.ManyToManyField(blank=True, to='main.materialpesca')),
                ('meses_mais_produtivos', models.ManyToManyField(blank=True, related_name='mais_produtivos', to='main.mes')),
                ('meses_menos_produtivos', models.ManyToManyField(blank=True, related_name='menos_produtivos', to='main.mes')),
                ('percepcao_captura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.percepcaocapturaopcao')),
                ('problemas', models.ManyToManyField(blank=True, to='main.problemapesca')),
                ('renda_pesca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rendapesca')),
                ('atividade_pos_captura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_captura', to='main.simnao')),
                ('existe_ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_coleta', to='main.simnao')),
                ('familiares_pescadores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familiares', to='main.simnao')),
                ('materiais_guardados', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_guardados', to='main.simnao')),
                ('participaria_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaria', to='main.simnao')),
                ('pesca_principal_renda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesca_principal', to='main.simnao')),
                ('possui_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro', to='main.simnao')),
                ('reaproveitamento_artesanato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artesanato', to='main.simnao')),
                ('turismo_pesca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.turismopescaopcao')),
                ('turismo_valoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.turismovalorizaopcao')),
                ('zonas_pesca', models.ManyToManyField(blank=True, to='main.zonapesca')),
            ],
        ),
    ]
